mail.smtp.host=smtp.resend.com
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.username=dailytaskmanager.project@gmail.com


mail.from=onboarding@resend.dev
mail.from.name=Daily Task Manager

otp.expiry.minutes=10
