mail.smtp.host=smtp-relay.brevo.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.username=dailytaskmanager.project@gmail.com

mail.from=dailytaskmanager.project@gmail.com
mail.from.name=Daily Task Manager

otp.expiry.minutes=10



